name: myapp
description: A exported flutter project from FUNCTION12


# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: '>=2.18.2 <3.0.0'

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  google_fonts: ^3.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^2.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  assets:
    - assets/page-1/images/leading-element.png
    - assets/page-1/images/st-trailing-icon.png
    - assets/page-1/images/logo-amik-png-1.png
    - assets/page-1/images/leading-icon.png
    - assets/page-1/images/leading-icon-S7i.png
    - assets/page-1/images/image-14.png
    - assets/page-1/images/image-8.png
    - assets/page-1/images/image-12.png
    - assets/page-1/images/image-3.png
    - assets/page-1/images/image-12-euv.png
    - assets/page-1/images/st-trailing-icon-Djv.png
    - assets/page-1/images/image-12-5YU.png
    - assets/page-1/images/image-3-46c.png
    - assets/page-1/images/logo-amik-png-1-coJ.png
    - assets/page-1/images/image-12-Ar4.png
    - assets/page-1/images/leading-icon-aba.png
    - assets/page-1/images/image-12-r7A.png
    - assets/page-1/images/image-8-84g.png
    - assets/page-1/images/image-10.png
    - assets/page-1/images/leading-icon-984.png
    - assets/page-1/images/image-3-iF2.png
    - assets/page-1/images/image-9.png
    - assets/page-1/images/image-10-mu2.png
    - assets/page-1/images/leading-icon-Pse.png
    - assets/page-1/images/leading-icon-968.png
    - assets/page-1/images/image-3-7Hr.png
    - assets/page-1/images/leading-icon-Cc8.png
    - assets/page-1/images/image-12-CwS.png
    - assets/page-1/images/image-3-Jkp.png
    - assets/page-1/images/image-3-ruN.png
    - assets/page-1/images/logo-amik-png-1-npG.png
    - assets/page-1/images/image-3-K7N.png
    - assets/page-1/images/image-9-SSt.png
    - assets/page-1/images/image-3-tYx.png
    - assets/page-1/images/image-13.png
    - assets/page-1/images/st-trailing-icon-s2p.png
    - assets/page-1/images/image-3-vKA.png
    - assets/page-1/images/image-3-nvL.png
    - assets/page-1/images/image-12-yRi.png
    - assets/page-1/images/image-12-Fjv.png
    - assets/page-1/images/image-12-jHa.png
    - assets/page-1/images/image-3-NWt.png
    - assets/page-1/images/image-8-kiC.png
    - assets/page-1/images/logo-amik-png-1-uoN.png
    - assets/page-1/images/image-3-YKA.png
    - assets/page-1/images/image-12-5pt.png
    - assets/page-1/images/image-3-9LC.png
    - assets/page-1/images/image-15.png
    - assets/page-1/images/image-12-xF2.png
    - assets/page-1/images/image-12-qqi.png
    - assets/page-1/images/image-12-LUx.png
    - assets/page-1/images/image-3-5vx.png
    - assets/page-1/images/image-12-ZUk.png
    - assets/page-1/images/image-12-nTJ.png
    - assets/page-1/images/image-12-5HJ.png
    - assets/page-1/images/image-3-Tyz.png
    - assets/page-1/images/image-12-cv4.png
    - assets/page-1/images/image-12-Lr4.png
    - assets/page-1/images/image-3-zyn.png
    - assets/page-1/images/image-6.png
    - assets/page-1/images/image-10-RKe.png
    - assets/page-1/images/image-3-Z4U.png
    - assets/page-1/images/image-3-89W.png
    - assets/page-1/images/logo-amik-png-1-oRz.png
    - assets/page-1/images/image-3-ihN.png
    - assets/page-1/images/image-3-rsz.png
    - assets/page-1/images/image-12-UAc.png
    - assets/page-1/images/image-12-1wE.png
    - assets/page-1/images/image-12-RVA.png
    - assets/page-1/images/image-3-zHN.png
    - assets/page-1/images/image-3-wkL.png
    - assets/page-1/images/image-6-zic.png
    - assets/page-1/images/image-3-gyN.png
    - assets/page-1/images/image-12-DQC.png
    - assets/page-1/images/image-3-cuW.png
    - assets/page-1/images/image-9-jck.png
    - assets/page-1/images/image-3-ZRz.png
    - assets/page-1/images/image-3-jRa.png
    - assets/page-1/images/image-3-eSc.png
    - assets/page-1/images/image-12-xue.png
    - assets/page-1/images/image-5.png
    - assets/page-1/images/image-5-5hr.png
    - assets/page-1/images/image-5-W9W.png
    - assets/page-1/images/image-5-rjA.png
    - assets/page-1/images/image-12-QxG.png
    - assets/page-1/images/image-5-aXJ.png
    - assets/page-1/images/image-5-Kzg.png
    - assets/page-1/images/image-11.png
    - assets/page-1/images/image-3-rvU.png
    - assets/page-1/images/image-12-sje.png
    - assets/page-1/images/image-1-bg.png
    - assets/page-1/images/image-3-HBE.png
    - assets/page-1/images/image-11-Dqa.png
    - assets/page-1/images/image-3-3we.png
    - assets/page-1/images/image-3-Vqa.png
    - assets/page-1/images/image-3-rAL.png
    - assets/page-1/images/image-3-xjA.png
    - assets/page-1/images/image-3-XQt.png
    - assets/page-1/images/image-11-45N.png
    - assets/page-1/images/image-3-AYQ.png
    - assets/page-1/images/image-3-WsA.png
    - assets/page-1/images/image-12-tDW.png
    - assets/page-1/images/image-1.png
    - assets/page-1/images/image-1-gU8.png
    - assets/page-1/images/avatars-3davatar30.png

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
